### ISSUE TITLE
1.20 support?

### ISSUE THREAD

**Issue by allanonmage** [OroArmorModding/Netherite-Plus-Mod#155]
*Describe the feature you'd like**
Fabric 1.20 support

**Describe how this feature adheres to the vanilla feel**
Vanilla is on it's 3rd or 4th version of 1.20

**Additional context**
I didn't see any update talking about the update, and I see that you just updated to 1.19.4, which is good to know that you're still updating it.  I think 1.19.4 is the hard part, and 1.20 is a smaller jump, so I'm hoping to see 1.20 soon.  I use Fabric, not Quilt.

**Comment by OroArmor** [comment]
1.20 already exists.

1.20.2 will come once I finish updating QSL and QFAPI

**Comment by OroArmor** [comment]
1.20 already exists.

1.20.2 will come once I finish updating QSL and QFAPI****

**Comment by allanonmage** [comment]
I don't see it on Modrinth, so that's why I didn't think it was available.  I just doublechecked, and it's still not on Modrinth.  I see it's available on Curseforge though.

On a related note, will the Quilt version work in Fabric?  I think that Quilt stuff is supposed to work on Fabric, but I haven't ran into that before.

**Comment by OroArmor** [comment]
Ah yeah, when I published the 1.20 version, I forgot to change the version on modrinth.

As for running on fabric, it's the other way around. Fabric mods work on quilt.

**Comment by allanonmage** [comment]
Here in The Future(TM), Modrinth still doesn't have the 1.20.x version, FYI.

**Comment by OroArmor** [comment]
Fixed! sorry for the delay.
